### ISSUE TITLE
Error when trying to insert start time

### ISSUE THREAD

**Issue by Gerry3019** [mrgadget/node-red-contrib-eztimer#14]
When trying to send an ontime programmatically the node always gives an error. Sending status shows that "on" has an error status. This was verified by node-red forum users. Duration also gives an error. It appears to be related to time entries as the days of the week can be set.

**Comment by mrgadget** [comment]
Hi @Gerry3019 - has this been tested on the latest build? I'm pretty sure this was all fixed in 1.1.3 as a result of #13 - this was only published to npm two days ago.

Let me know - if it is still present, can you please supply a flow that errors? Like a input -> timer -> debug or something similar.  Thanks!

**Comment by mrgadget** [comment]
Hey Gerry - I've just got up (GMT+12 timezone here) and seen your posts on the node forum. 
 Unfortunately as a new user I'm limited to 3 replies in a thread (frustrating!) so I can't respond.  

This node was born out of an annoyance that there wasn't a timer node that had a nice config UI that was pretty simple, so I took another node and edited it, and it's grown from there.  It was created to fill a need I had - and others have found it useful and use it which is great!

As discussed on the forum, just because a node exists in the library, doesn't mean it's even stable - it's up to us (devs) to ensure that, and we do that through issues like this one that you raised.   Bugs happen - especially when significant changes happen - because when it's a hobby project we can't be expected to test for ever eventuality.

If you find anything that's not working as expected - please do raise an issue (like you did) and I'm happy to look at it - also if there's  functionality that you think should be included in the node - log and issue for that too and we can discuss!

Cheers,
Ben.

**Comment by mrgadget** [comment]
Further [previous] discussion on this issue on the Node-RED forum [here](https://discourse.nodered.org/t/eztimer-programming-errors-timer-wont-start/15485).
