### ISSUE TITLE
eztimer crashing node-red

### ISSUE THREAD

**Issue by marc-gist** [mrgadget/node-red-contrib-eztimer#6]
node-red keeps crashing and I was able to capture this:

> 2 Jun 20:52:33 - [red] Uncaught Exception:
2 Jun 20:52:33 - ReferenceError: manual is not defined
    at status (/data/node_modules/node-red-contrib-eztimer/index.js:280:23)
    at Timeout.event.callback (/data/node_modules/node-red-contrib-eztimer/index.js:164:17)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

[edit]: note, i haven't changed anything via these nodes for some time, but just updated to latest version from previous...

**Comment by stu-carter** [comment]
I also have noticed that it is broken on an existing flow that used to work fine.  To test I installed it on a clean Raspian image using Node-red version 20.5 with eztimer 1.0.8 and the same issue is evident.

When I set the mode to 'ON = time of day' Off = duration', the following error is logged in the Node-RED debug output when the timer fired.  "TypeError: Cannot read property '3' of null"
![image](https://user-images.githubusercontent.com/45391135/58792154-e9594680-85f3-11e9-8636-4ef5aa25294c.png)

When I try to edit the timer and save it, the same error is logged in the debug output.

If I then change the on event to 'Manual', the following node status appears:
![image](https://user-images.githubusercontent.com/45391135/58792247-13ab0400-85f4-11e9-9120-e105529bcc94.png)

Sometimes it crashes Node-red, not sure what the condition has to be, but I added a second node, set the same trigger (time with duration) and it crashed when it triggered.
```
3 Jun 11:45:53 - [error] [eztimer:2b331582.569c5a] TypeError: Cannot read property '3' of null
3 Jun 11:45:53 - [info] Started modified nodes
3 Jun 11:46:00 - [red] Uncaught Exception:
3 Jun 11:46:00 - ReferenceError: manual is not defined
    at status (/home/pi/.node-red/node_modules/node-red-contrib-eztimer/index.js:280:23)
    at Timeout.event.callback (/home/pi/.node-red/node_modules/node-red-contrib-eztimer/index.js:164:17)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
3 Jun 11:46:02 - [info]
Welcome to Node-RED
```

For feeding animals, eztimer works perfectly, so thanks!  I have had to switch it out temporarily with BigTimer and using a trigger to get second granularity for on/off control until it gets fixed.

Thanks.

**Comment by mrgadget** [comment]
Apologies for introducing this bug - will look at this ASAP and update this issue. 

Thanks,
Ben.

**Comment by marc-gist** [comment]
Great node normally, so thank you... I'm surprised node-red doesn't deal with this more gracefully 😦

**Comment by stu-carter** [comment]
> 
> 
> Apologies for introducing this bug - will look at this ASAP and update this issue.
> 
> Thanks,
> Ben.
Thanks, happy to patch and test before you release if it helps.

**Comment by mrgadget** [comment]
Evening - have published [1.0.9](https://www.npmjs.com/package/node-red-contrib-eztimer) which should see your issue solved @marc-gist.  Was using a variable that I hadn't declared in the local scope.  Poor effort.  Have declared it now - and used it from the two manual locations so it should be good.

@stu-carter this is actually how it's meant to work - it's in the readme.md under [Times](https://github.com/mrgadget/node-red-contrib-eztimer/blob/develop/README.md#times) heading. You need to specify the duration in HH:mm:ss - so if you want 1 minute, use 00:01:00.  If you clear the '1' you have in the box, the placeholder text should show the format required.  But! Who reads the readme? I certainly don't most of the time.  So, to that end, I've put a couple of note boxes in the UI now too which should help stop this happening in the future.

Thanks for the comments too - I had no idea people would embrace yet _another_ timer, I just wanted a nice simple one that worked better for me! Pleased others are getting use out of it though - that's what github's all about.

Cheers,

**Comment by mrgadget** [comment]
Further to this @stu-carter - there's another gremlin in here with the manual on (in combination with the duration) that I'm still looking at - will come back to you.

**Comment by mrgadget** [comment]
@stu-carter - have pushed 1.0.10 to github (but not npm) - can you give it a shot and report back please?

**Comment by stu-carter** [comment]
Hi Mr Gadget, many thanks for the quick turnaround!

This now works great for my use-case and the note boxes are a great help to others.

Sorry about the lack of reading skills :)  I like the placeholder text in the field, but as the default is to populate the field with '0' when you change the dropdown, I never saw it.  The tip box makes it clear, but for icing on the cake, perhaps you could also default the duration value in the format '00:00:10' or even empty that field since '0' is accepted as a valid input when it isn't.

When I was testing your 1.0.10 for my own information on how it functions, I spotted 2 things which deviate from the docs...they don't matter for me (yet!) but I wanted you to know that there is gap which may catch someone else out.

**1.  Using time of day for on/off doesn't support seconds** 
Even though the docs and the new tooltip say you can use hh:mm:ss, the timer ignores the seconds and always fires on the minute.  e.g. on 17:00:15 and off 17:00:45 will fire at 17:00 and immediately fire off at 17:00.  If on is 17:00:45 and off is 17:01:30, it is on at 17:00 and off at 17:01.  This is confirmed when I send the 'info' command as the output always shows '00' for the seconds.

Perhaps this is an issue in the upstream schedex?..

**2. Cannot programmatically change the off duration**
If I configure a duration for the off event in the editor (00:00:01) but later send a payload of 'offtime 00:00:10', say, the duration doesn't change when the event is triggered.  It remained at 1 second, which I had originally set in the editor.  However, the offtime command does work if the off type is Time of Day.

I've attached the flow I used to reproduce this.

Thanks again.
[eztimer.txt](https://github.com/mrgadget/node-red-contrib-eztimer/files/3252977/eztimer.txt)

**Comment by mrgadget** [comment]
Thanks for the detailed report (and the flow) @stu-carter - I'll look to rectify these prior to releasing 1.0.10 I think.

The default is an interesting one - might see if I can default to 00:01:00 or similar.

Cheers

**Comment by mrgadget** [comment]
Back again - @stu-carter, can you re-clone/pull and have another go with 1.0.10.  I believe I've solved your issues, _hopefully_ without making any more!

**Comment by stu-carter** [comment]
Hi @mrgadget.

Thanks, that has addressed the two things.  

Sorry :), but one minor thing I noticed is that the info emitted by a Time of Day node doesn't reflect its on/off state correctly if it has been manually set on - although the status text says 'on', the info emitted says off.  The times are correct.  The node is configured to come on and off at a specific Time of Day.

It works fine when the node triggers itself when reaching the on-time and also works for a node that has a duration-based off event.

Please see the screen shot...
![image](https://user-images.githubusercontent.com/45391135/58950437-155cff00-878f-11e9-8b35-22a2e8570440.png)

Cheers!

**Comment by mrgadget** [comment]
Good catch!  Always good to have someone else testing, so thanks for that.

State was generated with logic (eg if on > off then it's off, else it's on).  I've changed this to a local variable which is updated each time an event is sent - I think this is more robust.

Try now please :) I think we're close...

**Comment by marc-gist** [comment]
Thanks for the work on this and updating other issues @mrgadget and testing @stu-carter 
sorry i've been too busy to help out testing 😦

**Comment by stu-carter** [comment]
Looks sound to me, thanks!

**Comment by mrgadget** [comment]
1.0.10 published to NPM.

**Comment by Icegames-dk** [comment]
![image](https://user-images.githubusercontent.com/63652094/90228804-2a173700-de17-11ea-804c-df21fef24969.png)

Hi

Any idea why I get this error ?

Node-RED version 1.1.1

**Comment by mrgadget** [comment]
None whatsoever sorry. That’s not a property I use. Can you please ensure you’re using the latest version (1.2.3) and if still an issue, please supply a test flow so I can see if I can reproduce. Thanks!

**Comment by mrgadget** [comment]
Actually! I think I do know - I checked again and there is some code in there that uses that property - it appears to be calling the function on `msg.payload`, so I'd suggest that the error you have there is caused by (somehow) sending the node a msg with a `null` payload.  Stab in the dark, but have a look.  Still keen on the test flow if you can't work it out.

Probably a valid issue and I could make it a nicer error.

**Comment by mrgadget** [comment]
@Icegames-dk please post any further comments in #35.
