### ISSUE TITLE
eztimer crashing node-red / 100 % CPU Load

### ISSUE THREAD

**Issue by B0F1B0** [mrgadget/node-red-contrib-eztimer#9]
my version: node-red-contrib-eztimer 1.0.11 (1.0.10 also not working, lower version not testet)

in your node properties the Sun Event "Night" is not working --> 100% CPU Load and Node Red Crashded
all other Sun Event are working

![NotWorking](https://user-images.githubusercontent.com/39368417/59508877-b0e92080-8eaf-11e9-9620-9818ec63bb59.png)

{
        "id": "84e078fb.7f3db8",
        "type": "eztimer",
        "z": "fb52a136.39c91",
        "name": "bad",
        "autoname": "solarNoon - night",
        "suspended": false,
        "sendEventsOnSuspend": false,
        "lat": "51",
        "lon": "34",
        "timerType": "1",
        "startupMessage": true,
        "ontype": "1",
        "ontimesun": "solarNoon",
        "ontimetod": "20:00:00",
        "onproperty": "payload",
        "onvaluetype": "bool",
        "onvalue": "true",
        "onoffset": 0,
        "onrandomoffset": 0,
        "offtype": "1",
        "offtimesun": "night",
        "offtimetod": "05:00:00",
        "offduration": "00:01:00",
        "offproperty": "payload",
        "offvaluetype": "bool",
        "offvalue": "false",
        "offoffset": 0,
        "offrandomoffset": 0,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "sun": true,
        "x": 70,
        "y": 320,
        "wires": [
            [
                "bf81d22b.b5a01"
            ]
        ]
    }

**Comment by mrgadget** [comment]
This is an interesting one, thanks for raising it - never would've seen it where I live.  This is due to a technicality - at your lat/long the `night` sun event is never triggered in summer due to your proximity to the north pole.

I use the suncalc library to calculate these events (why re-invent a perfectly good wheel) - see discussion on the `suncalc` issues page [here](https://github.com/mourner/suncalc/issues/70).

This all said, I agree that it should screw over your whole node-red instance, that's poor on my part.  In `1.0.12` (just published to npm now) I've handled this by ensuring `moment` returns a valid date before trying to schedule it.  If not, I update the node text:

![image](https://user-images.githubusercontent.com/700522/59538016-7aadae80-8f4c-11e9-8538-9f298898aa13.png)

... and spit out an error to the debug window where you can see the events that _are_ valid for your lat/long. 

![image](https://user-images.githubusercontent.com/700522/59538275-41c20980-8f4d-11e9-8c51-5ae497e32ed9.png)


Hope that helps.  If that doesn't work, you could always move closer to the equator :)

If you have a suggestion of a better way to handle this - I'm all ears, GitHub is a team sport!

Cheers,
Ben.

**Comment by B0F1B0** [comment]
Thanks for updating to newer Version.

There we have the salad,
B0F1B0
